import org.apache.tomcat.jni.Library;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


@RunWith(SpringJUnit4ClassRunner.class)
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    }
}
