import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import com.ApplicationSentinel;
import com.mapper.PersonMapper;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


@RunWith(SpringRunner.class)
@SpringBootTest(classes = ApplicationSentinel.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class LibraryTest {
	
	@Autowired
	PersonMapper personMapper;
	
    @Test 
    public void testSomeLibraryMethod() {
    	System.out.println(personMapper.getName(1));
    }
}
